apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: ghcr.io/burakbalim/api-gw
  local:
    push: true
    useBuildkit: true
    tryImportMissing: true

deploy:
  helm:
    releases:
      - name: api-gw
        #remoteChart: https://raw.githubusercontent.com/burakbalim/kubernetes-infra/master/zipped/service.tar.gz
        chartPath: /Users/burakbalim/codes/bbalim-github/kubernetes-infra/applications/charts/service_app_1
        valuesFiles:
          - /Users/burakbalim/codes/bbalim-github/kubernetes-infra/values/api-gw-values.yaml
        setValues:
          image.repository: ghcr.io/burakbalim/api-gw
          image.tag: "latest"

